//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_AddIns.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Word_AddIns.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string btn_OK {
            get {
                return ResourceManager.GetString("btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnAbout {
            get {
                object obj = ResourceManager.GetObject("btnAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 关于插件 的本地化字符串。
        /// </summary>
        internal static string btnAbout_Label {
            get {
                return ResourceManager.GetString("btnAbout_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于插件 的本地化字符串。
        /// </summary>
        internal static string btnAbout_ScreenTip {
            get {
                return ResourceManager.GetString("btnAbout_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示本插件版本以及版权等信息 的本地化字符串。
        /// </summary>
        internal static string btnAbout_SuperTip {
            get {
                return ResourceManager.GetString("btnAbout_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnAddWatermark {
            get {
                object obj = ResourceManager.GetObject("btnAddWatermark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 添加水印 的本地化字符串。
        /// </summary>
        internal static string btnAddWatermark_Label {
            get {
                return ResourceManager.GetString("btnAddWatermark_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用
        ///模板样式 的本地化字符串。
        /// </summary>
        internal static string btnApplyTemplate_Label {
            get {
                return ResourceManager.GetString("btnApplyTemplate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用模板样式 的本地化字符串。
        /// </summary>
        internal static string btnApplyTemplate_ScreenTip {
            get {
                return ResourceManager.GetString("btnApplyTemplate_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用定制模板样式到当前文档 的本地化字符串。
        /// </summary>
        internal static string btnApplyTemplate_SuperTip {
            get {
                return ResourceManager.GetString("btnApplyTemplate_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnExportPDF {
            get {
                object obj = ResourceManager.GetObject("btnExportPDF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 导出PDF 的本地化字符串。
        /// </summary>
        internal static string btnExportPDF_Label {
            get {
                return ResourceManager.GetString("btnExportPDF_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出为PDF 的本地化字符串。
        /// </summary>
        internal static string btnExportPDF_ScreenTip {
            get {
                return ResourceManager.GetString("btnExportPDF_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将当前文档导出为PDF文件 的本地化字符串。
        /// </summary>
        internal static string btnExportPDF_SuperTip {
            get {
                return ResourceManager.GetString("btnExportPDF_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnFeedback {
            get {
                object obj = ResourceManager.GetObject("btnFeedback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 反馈问题 的本地化字符串。
        /// </summary>
        internal static string btnFeedback_Label {
            get {
                return ResourceManager.GetString("btnFeedback_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题反馈 的本地化字符串。
        /// </summary>
        internal static string btnFeedback_ScreenTip {
            get {
                return ResourceManager.GetString("btnFeedback_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交当前系统以及Office版本、插件使用问题或改进建议 的本地化字符串。
        /// </summary>
        internal static string btnFeedback_SuperTip {
            get {
                return ResourceManager.GetString("btnFeedback_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnImportMarkdown {
            get {
                object obj = ResourceManager.GetObject("btnImportMarkdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 导入
        ///Markdown 的本地化字符串。
        /// </summary>
        internal static string btnImportMarkdown_Label {
            get {
                return ResourceManager.GetString("btnImportMarkdown_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Markdown文件 的本地化字符串。
        /// </summary>
        internal static string btnImportMarkdown_ScreenTip {
            get {
                return ResourceManager.GetString("btnImportMarkdown_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将Markdown文件转换并导入到当前Word文档中，不支持多文件导入 的本地化字符串。
        /// </summary>
        internal static string btnImportMarkdown_SuperTip {
            get {
                return ResourceManager.GetString("btnImportMarkdown_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnImportText {
            get {
                object obj = ResourceManager.GetObject("btnImportText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 导入
        ///文本文件 的本地化字符串。
        /// </summary>
        internal static string btnImportText_Label {
            get {
                return ResourceManager.GetString("btnImportText_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入文本文件 的本地化字符串。
        /// </summary>
        internal static string btnImportText_ScreenTip {
            get {
                return ResourceManager.GetString("btnImportText_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将TXT文件导入到当前Word文档中，支持多文件导入 的本地化字符串。
        /// </summary>
        internal static string btnImportText_SuperTip {
            get {
                return ResourceManager.GetString("btnImportText_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnModifyWatermark {
            get {
                object obj = ResourceManager.GetObject("btnModifyWatermark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 修改水印 的本地化字符串。
        /// </summary>
        internal static string btnModifyWatermark_Label {
            get {
                return ResourceManager.GetString("btnModifyWatermark_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnNewDocument {
            get {
                object obj = ResourceManager.GetObject("btnNewDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 创建
        ///新文档 的本地化字符串。
        /// </summary>
        internal static string btnNewDocument_Label {
            get {
                return ResourceManager.GetString("btnNewDocument_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文档 的本地化字符串。
        /// </summary>
        internal static string btnNewDocument_ScreenTip {
            get {
                return ResourceManager.GetString("btnNewDocument_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基于预置内容的文档模板创建新文档 的本地化字符串。
        /// </summary>
        internal static string btnNewDocument_SuperTip {
            get {
                return ResourceManager.GetString("btnNewDocument_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnRemoveStyles {
            get {
                object obj = ResourceManager.GetObject("btnRemoveStyles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 删除
        ///无用样式 的本地化字符串。
        /// </summary>
        internal static string btnRemoveStyles_Label {
            get {
                return ResourceManager.GetString("btnRemoveStyles_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除无用样式 的本地化字符串。
        /// </summary>
        internal static string btnRemoveStyles_ScreenTip {
            get {
                return ResourceManager.GetString("btnRemoveStyles_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文档中多余的样式，包括已经使用的多余样式，多余样式会在确认后删除 的本地化字符串。
        /// </summary>
        internal static string btnRemoveStyles_SuperTip {
            get {
                return ResourceManager.GetString("btnRemoveStyles_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnRemoveWatermark {
            get {
                object obj = ResourceManager.GetObject("btnRemoveWatermark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 删除水印 的本地化字符串。
        /// </summary>
        internal static string btnRemoveWatermark_Label {
            get {
                return ResourceManager.GetString("btnRemoveWatermark_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnSetDefault {
            get {
                object obj = ResourceManager.GetObject("btnSetDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 设为默认 的本地化字符串。
        /// </summary>
        internal static string btnSetDefault_Label {
            get {
                return ResourceManager.GetString("btnSetDefault_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为默认模板 的本地化字符串。
        /// </summary>
        internal static string btnSetDefault_ScreenTip {
            get {
                return ResourceManager.GetString("btnSetDefault_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将定制文档模板设为Word默认模板 的本地化字符串。
        /// </summary>
        internal static string btnSetDefault_SuperTip {
            get {
                return ResourceManager.GetString("btnSetDefault_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnUniformFont {
            get {
                object obj = ResourceManager.GetObject("btnUniformFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 统一字体 的本地化字符串。
        /// </summary>
        internal static string btnUniformFont_Label {
            get {
                return ResourceManager.GetString("btnUniformFont_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统一文档字体 的本地化字符串。
        /// </summary>
        internal static string btnUniformFont_ScreenTip {
            get {
                return ResourceManager.GetString("btnUniformFont_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将文档中所有文本设置为统一字体 - 微软雅黑 的本地化字符串。
        /// </summary>
        internal static string btnUniformFont_SuperTip {
            get {
                return ResourceManager.GetString("btnUniformFont_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnUniformTableStyle {
            get {
                object obj = ResourceManager.GetObject("btnUniformTableStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 统一表格 的本地化字符串。
        /// </summary>
        internal static string btnUniformTableStyle_Label {
            get {
                return ResourceManager.GetString("btnUniformTableStyle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统一表格样式 的本地化字符串。
        /// </summary>
        internal static string btnUniformTableStyle_ScreenTip {
            get {
                return ResourceManager.GetString("btnUniformTableStyle_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将文档中的所有表格应用统一的样式 的本地化字符串。
        /// </summary>
        internal static string btnUniformTableStyle_SuperTip {
            get {
                return ResourceManager.GetString("btnUniformTableStyle_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btnUpdateFields {
            get {
                object obj = ResourceManager.GetObject("btnUpdateFields", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 更新
        ///所有域 的本地化字符串。
        /// </summary>
        internal static string btnUpdateFields_Label {
            get {
                return ResourceManager.GetString("btnUpdateFields_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新所有域 的本地化字符串。
        /// </summary>
        internal static string btnUpdateFields_ScreenTip {
            get {
                return ResourceManager.GetString("btnUpdateFields_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新文档中的所有域，包括目录、页码等 的本地化字符串。
        /// </summary>
        internal static string btnUpdateFields_SuperTip {
            get {
                return ResourceManager.GetString("btnUpdateFields_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微软雅黑 的本地化字符串。
        /// </summary>
        internal static string DefaultFontName {
            get {
                return ResourceManager.GetString("DefaultFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confidential 的本地化字符串。
        /// </summary>
        internal static string DefaultWatermarkText {
            get {
                return ResourceManager.GetString("DefaultWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设计 的本地化字符串。
        /// </summary>
        internal static string DesignGroup_Label {
            get {
                return ResourceManager.GetString("DesignGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加水印时出错 的本地化字符串。
        /// </summary>
        internal static string Error_AddWatermark {
            get {
                return ResourceManager.GetString("Error_AddWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板应用失败 的本地化字符串。
        /// </summary>
        internal static string Error_ApplyTemplateFailed {
            get {
                return ResourceManager.GetString("Error_ApplyTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查水印失败 的本地化字符串。
        /// </summary>
        internal static string Error_CheckWatermarkFailed {
            get {
                return ResourceManager.GetString("Error_CheckWatermarkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比较模板失败 的本地化字符串。
        /// </summary>
        internal static string Error_CompareTemplateFailed {
            get {
                return ResourceManager.GetString("Error_CompareTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制模板失败 的本地化字符串。
        /// </summary>
        internal static string Error_CopyResourcesFailed {
            get {
                return ResourceManager.GetString("Error_CopyResourcesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新文档时出错 的本地化字符串。
        /// </summary>
        internal static string Error_CreateDocument {
            get {
                return ResourceManager.GetString("Error_CreateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除样式 的本地化字符串。
        /// </summary>
        internal static string Error_DeleteStyleFailed {
            get {
                return ResourceManager.GetString("Error_DeleteStyleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 {0} 不存在 的本地化字符串。
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件读取错误 的本地化字符串。
        /// </summary>
        internal static string Error_FileReadError {
            get {
                return ResourceManager.GetString("Error_FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败 的本地化字符串。
        /// </summary>
        internal static string Error_ImportFailed {
            get {
                return ResourceManager.GetString("Error_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径包含非法字符: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_InvalidPathChars {
            get {
                return ResourceManager.GetString("Error_InvalidPathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载水印文本失败 的本地化字符串。
        /// </summary>
        internal static string Error_LoadWatermarkFailed {
            get {
                return ResourceManager.GetString("Error_LoadWatermarkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理Markdown文件时出错 的本地化字符串。
        /// </summary>
        internal static string Error_MarkdownProcessFailed {
            get {
                return ResourceManager.GetString("Error_MarkdownProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改水印失败 的本地化字符串。
        /// </summary>
        internal static string Error_ModifyWatermarkFailed {
            get {
                return ResourceManager.GetString("Error_ModifyWatermarkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有打开的文档 的本地化字符串。
        /// </summary>
        internal static string Error_NoDocument {
            get {
                return ResourceManager.GetString("Error_NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择内容 的本地化字符串。
        /// </summary>
        internal static string Error_NoSelection {
            get {
                return ResourceManager.GetString("Error_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开邮件客户端失败 的本地化字符串。
        /// </summary>
        internal static string Error_OpenEmailFailed {
            get {
                return ResourceManager.GetString("Error_OpenEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pandoc转换失败:  的本地化字符串。
        /// </summary>
        internal static string Error_PandocFailed {
            get {
                return ResourceManager.GetString("Error_PandocFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到pandoc.exe，请从官方网站下载并安装: https://pandoc.org/installing.html 的本地化字符串。
        /// </summary>
        internal static string Error_PandocMissing {
            get {
                return ResourceManager.GetString("Error_PandocMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除水印时出错 的本地化字符串。
        /// </summary>
        internal static string Error_RemoveWatermarkFailed {
            get {
                return ResourceManager.GetString("Error_RemoveWatermarkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板文件未找到: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_TemplateNotFound {
            get {
                return ResourceManager.GetString("Error_TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行模板替换脚本时出错 的本地化字符串。
        /// </summary>
        internal static string Error_TemplateScriptFailed {
            get {
                return ResourceManager.GetString("Error_TemplateScriptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板替换脚本不存在 的本地化字符串。
        /// </summary>
        internal static string Error_TemplateScriptMissing {
            get {
                return ResourceManager.GetString("Error_TemplateScriptMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统一表格样式失败 的本地化字符串。
        /// </summary>
        internal static string Error_UniformTableStyleFailed {
            get {
                return ResourceManager.GetString("Error_UniformTableStyleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新域失败 的本地化字符串。
        /// </summary>
        internal static string Error_UpdateFieldsFailed {
            get {
                return ResourceManager.GetString("Error_UpdateFieldsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印检查失败 的本地化字符串。
        /// </summary>
        internal static string Error_WatermarkCheckFailed {
            get {
                return ResourceManager.GetString("Error_WatermarkCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到名为&apos;watermark&apos;的水印 的本地化字符串。
        /// </summary>
        internal static string Error_WatermarkNotFound {
            get {
                return ResourceManager.GetString("Error_WatermarkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word模板文件(Normal.dotx)不存在 的本地化字符串。
        /// </summary>
        internal static string Error_WordTemplateMissing {
            get {
                return ResourceManager.GetString("Error_WordTemplateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string ExportGroup_Label {
            get {
                return ResourceManager.GetString("ExportGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string ImportGroup_Label {
            get {
                return ResourceManager.GetString("ImportGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择字体大小: 的本地化字符串。
        /// </summary>
        internal static string Label_FontSize {
            get {
                return ResourceManager.GetString("Label_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入水印文字: 的本地化字符串。
        /// </summary>
        internal static string Label_WatermarkText {
            get {
                return ResourceManager.GetString("Label_WatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap mnuWatermark {
            get {
                object obj = ResourceManager.GetObject("mnuWatermark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 水印 的本地化字符串。
        /// </summary>
        internal static string mnuWatermark_Label {
            get {
                return ResourceManager.GetString("mnuWatermark_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印操作 的本地化字符串。
        /// </summary>
        internal static string mnuWatermark_ScreenTip {
            get {
                return ResourceManager.GetString("mnuWatermark_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加、修改或删除文档水印 的本地化字符串。
        /// </summary>
        internal static string mnuWatermark_SuperTip {
            get {
                return ResourceManager.GetString("mnuWatermark_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        internal static string MoreGroup_Label {
            get {
                return ResourceManager.GetString("MoreGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即将删除以下样式:
        ///{0}
        ///
        ///确认要删除吗？ 的本地化字符串。
        /// </summary>
        internal static string Msg_ConfirmRemoveStyles {
            get {
                return ResourceManager.GetString("Msg_ConfirmRemoveStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要替换Word默认模板吗？ 的本地化字符串。
        /// </summary>
        internal static string Msg_ConfirmTemplateReplace {
            get {
                return ResourceManager.GetString("Msg_ConfirmTemplateReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档中的所有域已更新完成 的本地化字符串。
        /// </summary>
        internal static string Msg_FieldsUpdated {
            get {
                return ResourceManager.GetString("Msg_FieldsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理.... 的本地化字符串。
        /// </summary>
        internal static string Msg_InProcessing {
            get {
                return ResourceManager.GetString("Msg_InProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Markdown文件已成功导入 的本地化字符串。
        /// </summary>
        internal static string Msg_MarkdownImportSuccess {
            get {
                return ResourceManager.GetString("Msg_MarkdownImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有需要删除的样式 的本地化字符串。
        /// </summary>
        internal static string Msg_NoStylesToRemove {
            get {
                return ResourceManager.GetString("Msg_NoStylesToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前文档中没有表格 的本地化字符串。
        /// </summary>
        internal static string Msg_NoTable {
            get {
                return ResourceManager.GetString("Msg_NoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在导入文件: {0} 的本地化字符串。
        /// </summary>
        internal static string Msg_ProcessingFile {
            get {
                return ResourceManager.GetString("Msg_ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板替换任务已挂起
        ///将在Word退出后自动替换模板 的本地化字符串。
        /// </summary>
        internal static string Msg_ReplaceTemplatePending {
            get {
                return ResourceManager.GetString("Msg_ReplaceTemplatePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档样式清理成功 的本地化字符串。
        /// </summary>
        internal static string Msg_StyleRemovedSuccess {
            get {
                return ResourceManager.GetString("Msg_StyleRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定制模板已应用到当前文档 的本地化字符串。
        /// </summary>
        internal static string Msg_TemplateApplySuccess {
            get {
                return ResourceManager.GetString("Msg_TemplateApplySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功导入 {0}/{1} 个文本文件 的本地化字符串。
        /// </summary>
        internal static string Msg_TextImportSuccess {
            get {
                return ResourceManager.GetString("Msg_TextImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档字体已统一设置为{0} 的本地化字符串。
        /// </summary>
        internal static string Msg_UniformFontSuccess {
            get {
                return ResourceManager.GetString("Msg_UniformFontSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功统一所有表格样式 的本地化字符串。
        /// </summary>
        internal static string Msg_UniformTableStyleSuccess {
            get {
                return ResourceManager.GetString("Msg_UniformTableStyleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印已成功添加 的本地化字符串。
        /// </summary>
        internal static string Msg_WatermarkAdded {
            get {
                return ResourceManager.GetString("Msg_WatermarkAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印已成功修改 的本地化字符串。
        /// </summary>
        internal static string Msg_WatermarkModified {
            get {
                return ResourceManager.GetString("Msg_WatermarkModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印已成功删除 的本地化字符串。
        /// </summary>
        internal static string Msg_WatermarkRemoved {
            get {
                return ResourceManager.GetString("Msg_WatermarkRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板工具 的本地化字符串。
        /// </summary>
        internal static string RibbonTab_Label {
            get {
                return ResourceManager.GetString("RibbonTab_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板 的本地化字符串。
        /// </summary>
        internal static string TemplateGroup_Label {
            get {
                return ResourceManager.GetString("TemplateGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于插件 的本地化字符串。
        /// </summary>
        internal static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        internal static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出PDF 的本地化字符串。
        /// </summary>
        internal static string Title_ExportPDF {
            get {
                return ResourceManager.GetString("Title_ExportPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入操作失败 的本地化字符串。
        /// </summary>
        internal static string Title_ImportFailed {
            get {
                return ResourceManager.GetString("Title_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Markdown文件 的本地化字符串。
        /// </summary>
        internal static string Title_ImportMarkdown {
            get {
                return ResourceManager.GetString("Title_ImportMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入文本文件 的本地化字符串。
        /// </summary>
        internal static string Title_ImportText {
            get {
                return ResourceManager.GetString("Title_ImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Title_Notice {
            get {
                return ResourceManager.GetString("Title_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要导入的Markdown文件 的本地化字符串。
        /// </summary>
        internal static string Title_SelectMarkdownFiles {
            get {
                return ResourceManager.GetString("Title_SelectMarkdownFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要导入的文本文件 的本地化字符串。
        /// </summary>
        internal static string Title_SelectTextFiles {
            get {
                return ResourceManager.GetString("Title_SelectTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板替换确认 的本地化字符串。
        /// </summary>
        internal static string Title_TemplateReplace {
            get {
                return ResourceManager.GetString("Title_TemplateReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加水印 的本地化字符串。
        /// </summary>
        internal static string Title_WatermarkDialog {
            get {
                return ResourceManager.GetString("Title_WatermarkDialog", resourceCulture);
            }
        }
    }
}
